### ISSUE TITLE
"could not make request round trip: target flag is required."

### ISSUE THREAD

**Issue by flangewad** [pivotal-cf/om#94] opened 2017-07-25 12:56 UTC
We're running `import-installation`. If the protocol is missing from the target, the error is pretty cryptic:

```
could not execute "import-installation": could not check Ops Manager status: could not make request round trip: target flag is required. Run `om help` for more info.
```

Should this be changed to something more indicative of the actual issue?

**Comment by ryanmoran** [comment] 2017-07-25 16:53
@flangewad This is a duplicate of https://github.com/pivotal-cf/om/issues/83, but that reporter does not seem to be working toward a solution. I will have someone take a look at this. Thanks!

**Comment by acrmp** [comment] 2017-08-01 04:51
Hi @flangewad,

Thanks for reporting this. I've pushed a change that should allow the target to be specified without the protocol for unauthenticated endpoints.

**Closed by acrmp** 2017-08-01 04:51 UTC
Labels: in progress
