### ISSUE TITLE
`om curl` replaces `%x` to `!x(MISSING)` in the output    (x can be any char)

### ISSUE THREAD

**Issue by syslxg** [pivotal-cf/om#49] opened 2017-03-10 00:22 UTC
to reproduce the bug

- in opsman UI, set  ERT tile/Custom Branding/Company Name' to `Sand%box`
- download the manifest use `om -k -t $OPSMAN_URI -u $OPSMAN_USERNAME -p $OPSMAN_PASSWORD curl -p /api/v0/staged/products/cf-xxxxx/manifest  | grep company_name `, you will get `Sand%!b(MISSING)ox`

**Comment by ryanmoran** [comment] 2017-03-10 00:24
Closing because this is a dupe of https://www.pivotaltracker.com/story/show/141460021

**Closed by ryanmoran** 2017-03-10 00:24 UTC
Labels: unscheduled
