### ISSUE TITLE
om configure-product should be enhanced to support collections 

### ISSUE THREAD

**Issue by sadvani** [pivotal-cf/om#207] opened 2018-07-19 21:22 UTC
Configuring or Editing collections in OpsManager via the API behaves in a non deterministic manner. Some service tiles (MySQL v2, maybe others) use collections to define Service Plans in the tile. Currently, if a collection has multiple records, and a change is being made to one collection record by passing on only the GUID of the record in question along with the change, OpsManager will delete all other collection records. This means that only the record that the Operator was trying to edit will be saved. Additionally, if an operator tries to change a collection record without specifying a GUID, OpsManager will proceed to delete all records and create a new one with a new GUID. This issue has been seen a few times with the MySQL Tile [1]. We flagged this issue with the Pcf-Pipelines and PAS teams and they suggested we open an issue in this repo [2]

A workaround for this issue is for om configure-product to send all GUIDS and plans on every PUT. 

[1] https://github.com/pivotal-cf/pcf-pipelines/issues/332
[2] https://pivotal.slack.com/archives/C0554UNSS/p1531941382000046

**Comment by sadvani** [comment] 2018-07-19 21:33
I believe it does always fail. You could either use the MySQL v2 tile or the OpsManager example product. In the MySQL case, you will have to deploy the entire once and then use configure-product and deploy again. This deploy should fail because the GUIDs associated with the deployed service plans will have changed. 

You can use the example tile by just using configure-product and noticing the strange behavior of records getting deleted, GUIDs changing, etc.

**Comment by mcwumbly** [comment] 2018-07-19 22:05
Cool, I'll assume that's the case. We'll try to prioritize this ourselves at some point if no one else gets to it first, but I'm throwing a `pr-welcome` on it in the meantime.

**Comment by jtarchie** [comment] 2018-09-18 18:37
@sadvani and @mcwumbly, are you able to review the PR from @calebwashburn. I've been able to see that the code works, but I don't have a way (or knowledge) on how reproduce this issue.

**Comment by sadvani** [comment] 2018-10-01 21:03
@mcwumbly @jtarchie @calebwashburn is this issue fixed?

**Comment by calebwashburn** [comment] 2018-10-01 21:27
@sadvani Believe so

**Comment by fredwangwang** [comment] 2018-10-01 21:27
yes, this pr https://github.com/pivotal-cf/om/pull/227 has been pulled in. We validated using @calebwashburn's gist. Do you still see a problem?

**Comment by sadvani** [comment] 2018-10-01 23:27
Perfect, thanks so much @calebwashburn @fredwangwang. 

Is there a specific version of OM that I should tell the customer to upgrade to?

**Comment by fredwangwang** [comment] 2018-10-02 03:49
master, there is no release cut since the fix introduced.

**Comment by jtarchie** [comment] 2018-10-16 21:57
@sadvani: I think we might have to revert this change. An issue #274 shows that we cannot rely on a collection having a `name` property to match with the `guid`. We don't have any guarantees with a collection that there is uniqueness on a single property of a collection. This broke other collections.

We might have to be _stronger_ on this an enforce the any element on a collection that has to be persisted and updated (not removed and recreated) should always have a `guid`.

**Comment by anEXPer** [comment] 2018-10-17 22:49
@dsboulder I understand you're currently backing @sadvani up as Ops Man PM. Any thoughts on this?

**Comment by dsboulder** [comment] 2018-11-06 18:39
I validated that if collection records as passed with a "guid" field, then those existing records will be found and updated.  Otherwise we'll consider them new records (and delete any unmatched-by-guid records at the end).

**Comment by gregbarkerdcsg** [comment] 2019-09-09 17:56
Any updates here? I recently encountered what I think is this issue when upgrading the Redis Enterprise tile. I had issues with the Broker Registrar errand where it was trying to create new plans with different GUIDs but the same plan names. I had to rename existing plans, let it create the new plans alongside the existing plans, and then migrate each service to the renamed plans. Then the broker registrar errand was run manually again to delete the original plans that it had trouble with.

**Comment by kcboyle** [comment] 2019-09-09 18:03
We're still discussing a way to do this. the problem with enforcing the GUID as we described above is that you could _not_ use the same config to re-configure a new env. This is not desired behavior. 

We discussed potentially doing something like this (a proposal from the story in our tracker):
can `om` lookup the config for a nameless collection and do a comparison to see if there are any changes (other than guid) and, if there are no changes, grab the existing guid and inject it when `configure-product` is run. This would be an alternative to forcibly requiring a guid in the config file for `configure-product`, but might not be possible. This is worth exploring to allow OpsMan to keep its contract with BOSH (guid being guaranteed unique) but allow for a good user experience that will not "change" the guid when the configuration for a collection is the same. 

PROS:
- we can do this now
- good customer experience
- no breaking change
CONS:
- potentially difficult
- requires multiple calls to the OpsManager API before actually configuring the product (if the `name` field does not exist) to validate that the configuration is the same. (additional complexity for `configure-product`)

**Comment by gregbarkerdcsg** [comment] 2019-09-09 18:18
OM is the thing that causes the GUID issue. Manually changing within OpsMan UI does not. Is that accurate? 
Therefore any PCF Platform Automation that deals with a collection could trigger this issue?

**Comment by kcboyle** [comment] 2019-09-25 22:55
it is not `om` causing the issue, but the Ops Manager API that is returning this value to us. 

You are correct in that the UI does not have this problem, but `om` is limited by what the API can return to us. Because each tile team on Pivnet is in control of what their collections look like and _optionally_ define a name, we have a hard time using the API to handle collections because there is nothing else we can key off of. This is not an issue with Platform Automation, but with the tile authors themselves. The optimal fix for this issue is to require every tile team to name their collections, but this is a much larger undertaking.

**Comment by mboldt** [comment] 2019-11-04 17:54
I find it quite unfair to claim that the cause of this issue tile authors not having a `name` property in every collection. The root cause seems to be this limitation in the Ops Manager API:

> the problem with enforcing the GUID as we described above is that you could not use the same config to re-configure a new env. This is not desired behavior.

This issue existed before the `name` workaround was added.

If, going forward, the expectation is that every `collection` has a `name` field:

1. This needs to be documented in the [Tile Developers Guide](https://docs.pivotal.io/tiledev/) (at a minimum in the [`collection` field documentation](https://docs.pivotal.io/tiledev/property-template-references.html#collection), perhaps there are other important places to include this). Could we get that on the `om` backlog, since this is where the requirement is coming from?

2. This needs to be widely communicated to our partner tile authors as something that needs to be updated in their tiles. My team (Platform Engineering) can help with this once the expectations are well-documented.

In the meantime, it sounds like the workaround for customers would be to manage the `guid` fields, specific to each Ops Manager environment. Not a great experience, but could get them by, right?

**Comment by jtarchie** [comment] 2019-11-04 18:15
@mboldt, It is issue for the tile authors and the OpsManager API.

For tile authors, because there's an experience of their tile that doesn't work for users who have request being able to duplicate across multiple foundations.
For Ops Manager, because there there's an experience with trying to extract configurations.
The fact that this is an issue and all you have not talk to each other about this is systematic problem.

The above was a proposal as we were trying to solve this from a Platform Automation standpoint.

We have talk to Ops Manager about it.
We have talk to a tile team(s?) about this.
Here is a [story](https://www.pivotaltracker.com/story/show/166918394) that reflects some of those discussions.

We have made an effort to communicate this issue to the right people.
We've reprioritized based on other features our product needs.
If you would, please, as a tile team, like to work with the OpsManager team to fix the user experience.
They way your users will be happier about using your product.

**Comment by kcboyle** [comment] 2020-03-09 19:57
For those still watching/following this issue, does anyone have any other ideas around what `om` can do to mitigate this issue? this comes up as a team question every now and then, and we can't really think of a good solution. Happy to reopen this discussion to get some fresh ideas/insight around this problem area

@calebwashburn @jtarchie @anEXPer @sadvani @mcwumbly @dsboulder @gregbarkerdcsg

**Comment by kcboyle** [comment] 2020-05-01 15:39
If we can't think of any good viable solutions, I'm going to see about closing this issue for now. If anyone has any ideas for us to work off of, feel free to reopen the discussion

**Comment by mrdavidlaing** [comment] 2020-08-04 11:51
Based on the following analysis - [om configure-product should be enhanced to support collections - Analysis & Recommendations](https://docs.google.com/document/d/1ZWX7twODLiyGTXnYP6xWtJZnrkLaJw2VTRBAUkbdz5I/edit?ts=5f1b3063#)

I believe we can address the majority of remaining issues with the following changes:

1. [om cli] Use collection item hash to find GUID rather than name - this covers all cases where no change is being made
1. [om cli] Expand the list of “logical Id” fields from `name` to include `key` or any field ending in `name` - this covers nearly all changes *except* those where the logical key field itself is being changed

**Comment by mrdavidlaing** [comment] 2020-08-12 11:58
Once PRs #502 and #503 have been merged; using `om` in a GitOps workflow will associate existing GUIDs to collection items as follows:

1.  When **no** changes have been made; no GUIDs will be regenerated and no changes will show in `om bosh-diff`.  ie:
    * After exporting tile config: `om staged-config -p example-product -c > example-product-config.yml`
    * When configuring the tile using that config (having made no changes): `om configure-product -c example-product-config.yml`
    * `om bosh-diff` will show no changes
1.  When making changes to collection items that have a _logical key_ field (named `name`, `key` or ending in `name`); existing GUIDs will be associated with the changed collection item causing an edit of the existing item rather than a deletion and recreation (with a new `guid`).  ie:
    *  When configuring the tile with a `example-product-config.yml` that contains the following changes:
        ![image](https://user-images.githubusercontent.com/227505/90012362-28286900-dc9b-11ea-9f7c-84d603216375.png)
    *  `om bosh-diff` will show the following edits to existing collection items:
        ![image](https://user-images.githubusercontent.com/227505/90012502-658cf680-dc9b-11ea-88ed-52e56027c0a7.png)


_Known Issues_
* GUID association does not work for collections items that have a secret field AND no logical key
* GUID association does not work when changing the value of the _logical key_ field
* GUID association does not work when changing an item that doesn't have a _logical key_ field

**Comment by kcboyle** [comment] 2020-08-12 18:21
This was fixed by the associated PRs.

We're happy to see this long-running issue finally addressed!

**Closed by kcboyle** 2020-08-12 18:21 UTC
Labels: breaking-change, pr welcome, scheduled

**Comment by kcboyle** [comment] 2020-10-07 16:55
Another bug was discovered after the merging fix was done.
The feedback:
```
Our work flow ...
Upload and manually configure HW2.
 2.  Apply changes.
 3.  Download config for running tile and convert to a template for use in our TF code.
We've had a number of upgrades recently and it appears the OM cli that is bundled in the Platform automation (OM cli v6.3.0) doesn't work with the scrape job collection in the HW2 tile.
Further investigation revealed that OM cli v6.1.1 (on my workstation) works, and newer versions, both opensource and supported, do not work with the healthwatch2 config when more than 1 scrape job is present.
There was of discussion in the OM cli repo regarding collections and impacts to tile creators.
```
Digging into it, 
- HW has a collection of scrape jobs used by prometheus to scrape metrics from different endpoints. Similar to how `-p-mysql` defines plans
```yml
#edited-healthwatch-config
.properties.scrape_configs:
    value:
    - ca: |
        -----BEGIN CERTIFICATE-----
        <REDACTED>
        -----END CERTIFICATE-----
      insecure_skip_verify: true
      scrape_job: |
        job_name: 'ec2'
        scheme: https
        ec2_sd_configs:
        - region: us-west-2
          port: 9100
        relabel_configs:
        # Only monitor instances with a MetricsKey tag matchine mine
        - source_labels: [__meta_ec2_tag_MetricsKey]
          regex: pws dark ci bwAvFbeC5X
          action: keep
        - source_labels: [__meta_ec2_tag_Name]
          target_label: name_tag
        - source_labels: [__meta_ec2_availability_zone]
          target_label: availability_zone
        - source_labels: [__meta_ec2_instance_id]
          target_label: instance_id
      server_name: null
    - ca: |
        -----BEGIN CERTIFICATE-----
        <REDACTED>
        -----END CERTIFICATE-----
      insecure_skip_verify: false
      scrape_job: |-
        job_name: 'fluentd'
        metrics_path: /aggregated_metrics
        static_configs:
        - targets:
          - fluentd.<REDACTED>.com:9200
      server_name: null
```
When uploading/configure HW using 6.1.1, both expected jobs show up in the HW config
when uploading/configure HW using 6.1.2, only the second job appears in the config
This was on OpsMan 2.9.11 using om 6.3.0

**Comment by mrdavidlaing** [comment] 2020-10-08 10:12
I suspect the issue has to do with the nested collections (eg `scrape_job.relabel_configs`) - that wasn't a use case I expected / tested when working on the original PR(s)

Let me know if I can help.
