### ISSUE TITLE
Apply changes fails against latest 2.5.0 OpsManager

### ISSUE THREAD

**Issue by edwardecook** [pivotal-cf/om#328] opened 2019-02-22 09:51 UTC
OpsManager have recently changed their version string formatting to include the patch number, e.g. 2.5.0-build.128. This results in failures when trying to apply-changes via om such as:
```
panic: invalid version: 2.5.0-build.128

goroutine 1 [running]:
github.com/pivotal-cf/om/api.Info.VersionAtLeast(0xc00033c130, 0xf, 0x2, 0x2, 0x0)
	/tmp/build/80754af9/om/api/info_service.go:29 +0x21a
github.com/pivotal-cf/om/commands.ApplyChanges.Execute(0xcb4400, 0xc00001db30, 0xcaabe0, 0xc00001db80, 0xcb0640, 0xc00001d8b0, 0xca9620, 0xc00027d180, 0x2540be400, 0x0, ...)
	/tmp/build/80754af9/om/commands/apply_changes.go:70 +0x23d
github.com/pivotal-cf/jhanda.CommandSet.Execute(0xc0002b3020, 0x7ffdffce8419, 0xd, 0xc00001c080, 0x2, 0x2, 0x7, 0x0)
	/tmp/build/80754af9/go/pkg/mod/github.com/pivotal-cf/jhanda@v0.0.0-20180509215011-1b5ae1681a45/command_set.go:25 +0x11c
main.main()
	/tmp/build/80754af9/om/main.go:201 +0x55b2
```

This is looks like it is due to https://github.com/pivotal-cf/om/blob/4e25e48ef5869281c0e3b9cda691d0427a02b6e7/api/info_service.go#L16-L36

We (PCF Redis) will have a look at submitting a PR for this.

**Comment by kcboyle** [comment] 2019-02-22 21:17
What command are you running that is causing this issue? are you using an internal dev build of OpsMan, or the alpha/betas? 
We tested apply-changes with `ops-manager-vsphere-2.5.0-build.128.ova` and were able to `apply-changes` and `export-installation` with no issue.

**Comment by edwardecook** [comment] 2019-02-22 21:35
Hi @kcboyle, makes sense.

We're running `om -k apply-changes --product-name "p-redis"` (with some additional auth stuff) and using Toolsmiths' GCP pool envs, which report as having version `2.5.0-build.128`, I don't know exactly what their source for builds is.

**Comment by kcboyle** [comment] 2019-02-25 22:50
For context in the Open Source community, Ed and I have been having a conversation. Putting it in here:
(edwardecook):
So I think we were under the impression that there had been a change with how OpsManager was versioning their builds. The issue that we have is that when we are using toolsmith pools we can't specify anything beyond minor version and we just get whichever build the toolsmith team have pulled

(kcboyle):
that is really good contextual info for us. Give us the rest of today and tomorrow to narrow down _exactly_ when the error occurs (to give better release notes, and know the extent of this error for other teams)  and we can pull in this PR then

(kcboyle):
Hi again, ed! so we tested running apply changes using the most recent beta installed on gcp using the toolsmiths tooling. We installed the redis tile and used `om apply-changes`, and got no failures. That's not to say that we do not want to bring in the PR, but can you help us to recreate the error on our end? I feel very strongly about well thought-out and honest release notes, and I would not know what to write for this bug fix

**Comment by jplebre** [comment] 2019-02-26 10:46
Hey @kcboyle we tried this morning to replicate the issue, here's how we (pcf-redis) run into the issue:
- Get a Toolsmiths pooled env on the latest us_2_5 pool
- Install the Redis for PCF tile 1.14 or 2.0 (the only ones that support us_2_5) and apply changes.
- Try to unstage and apply changes to product by running:
```
om -k unstage-product --product-name "p-redis"
om -k apply-changes --product-name "p-redis"
```
And returns the following:
![image](https://user-images.githubusercontent.com/5503088/53407181-75375300-39b3-11e9-87fd-af39afc45ccf.png)

```
panic: invalid version: 2.5.0-build.135

goroutine 1 [running]:
github.com/pivotal-cf/om/api.Info.VersionAtLeast(0xc0003747d0, 0xf, 0x2, 0x2, 0x0)
	/tmp/build/80754af9/om/api/info_service.go:29 +0x21a
github.com/pivotal-cf/om/commands.ApplyChanges.Execute(0x18b7680, 0xc000099a90, 0x18adda0, 0xc000099ae0, 0x18b3800, 0xc000099810, 0x18ac6e0, 0xc000281260, 0x2540be400, 0x0, ...)
	/tmp/build/80754af9/om/commands/apply_changes.go:70 +0x23d
github.com/pivotal-cf/jhanda.CommandSet.Execute(0xc0002b8ff0, 0x7ffeefbfeaa2, 0xd, 0xc00001c140, 0x2, 0x2, 0x7, 0x0)
	/tmp/build/80754af9/go/pkg/mod/github.com/pivotal-cf/jhanda@v0.0.0-20180509215011-1b5ae1681a45/command_set.go:25 +0x11c
main.main()
	/tmp/build/80754af9/om/main.go:201 +0x55b2
exit status 2
```
We are happy to pair with you to replicate this product, it would take about 40min to prepare an environment, or we can share a pre-prepared environment with you.

**Comment by kcboyle** [comment] 2019-02-26 16:18
Ok @jplebre 

So the issue isn't with _installing_ redis, but with _deleting_ redis. And this is not so much an issue with the generic `apply-changes`, but with the selective-deploy aspect of `apply-changes`. We'll accept this PR. Thank you for the backwards compatibility and helping us to work through this.

**Comment by kcboyle** [comment] 2019-02-26 16:34
PR merged. Closing issue.

**Closed by kcboyle** 2019-02-26 16:34 UTC

**Comment by jplebre** [comment] 2019-03-04 09:06
Thank you @kcboyle
