### ISSUE TITLE
import-installation sometimes fails

### ISSUE THREAD

**Issue by dark5un** [pivotal-cf/om#121] opened 2017-11-29 11:07 UTC
We are getting errors when upgrading Opsmanager whilst following the documentation at https://docs.pivotal.io/pivotalcf/1-11/customizing/upgrading-pcf.html#upgrade_ops but using `om` to perform the import-installation step. `om` manages to import-installation but then Opsmanager becomes unresponsive and the upgrade fails:

```
om --target "opsman.$PCF_DOMAIN" \ 
--skip-ssl-validation \ 
--request-timeout 86400 import-installation \ 
--installation installation-settings/opsman-settings.zip \ 
--decryption-passphrase "$(cut -d= -f 2 om-decrypt/decryption-passphrase)"

processing installation 
beginning installation import to Ops Manager 
8.49 GiB / 8.49 GiB [===========================================] 100.00% 8m58s 
41m40s elapsed, waiting for response from Ops Manager... 
could not execute "import-installation": could not check Ops Manager Status: could not make request round trip: Get https://opsman.example.com/login/ensure_availability: dial tcp 52.81.112.19:443: i/o timeout failed 
```

**(The ip and the domain has been changed)**

We have a reproducible script to perform the upgrade, however it is not reliable and Opsman seems to randomly fail to import settings.

**Comment by utako** [comment] 2017-12-08 19:38
Hi @dark5un,

Are you running your script in Concourse?

Would it be possible for you to do the following the next time you see this happen?

> If this happens again, it would be nice to look at the tcp connection state of the om request on the client side and the ops manager side (running netstat -an would give you this info). It would also be nice to know how traffic reaches your opsman (for instance is there a load balancer in the path, haproxy, etc). This would help us further debug the issue.

If you are running into this problem, we think it might be associated with the Concourse issue described [here](https://github.com/pivotal-cf/om/issues/104#issuecomment-342248874). Regardless, it'd be great to get some more networking related data to help figure out what's going on.

Thanks,
@kenchenpcf and @utako, PCF Releng Team

**Comment by madamkiwi** [comment] 2017-12-13 22:31
Furthemore, can you go to the https://example.com/debug page and show us the logs of why the Opsman process crashed? It would be nice to give a stack trace to the Opsman team.

cc @kkallday

**Comment by utako** [comment] 2018-01-04 17:41
Hi @dark5un,

As we're unable to reproduce this error ourselves and help you further, I'm going to go ahead and close this issue. If this happens again and you're able to get us the logs and netstat data, we'll be happy to spend some more time working with you.

Thanks,
@utako, PCF Releng

**Closed by utako** 2018-01-04 17:41 UTC
Labels: in progress
