### ISSUE TITLE
configure-bosh does not set director config info.

### ISSUE THREAD

**Issue by DonBower** [pivotal-cf/om#82] opened 2017-06-21 23:47 UTC
When configuring the --director-config options with the configure-bosh command, I get a message it's done, but no changes are observed.
Here is the command I run:
```
echo "Try Director Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --director-configuration "${D_PROPERTIES}"
```
Here is the output I get:
```
Try Director Config
configuring director options for bosh tile
finished configuring bosh tile
```
No changes are made in the `Director Config` pane of the Ops Manager Director tile.
This is prior to initial `Apply Changes` (i.e. fresh install)
All of the other configure-bosh sub-commands work.

**Comment by davewalter** [comment] 2017-06-22 03:38
Hi @DonBower.

Without knowing what the before and after state of your Ops Manager director configuration is, as well as the properties that you are trying to set, the iaas you are deployin to and the version of `om` that you are using, it is very hard to attempt to figure out what the problem might be. One general piece of advice I can offer is to look at the Ops Manager UI log (/debug/rails_log) to see if your request is there and how it was processed by Ops Manager.

Hope this helps.

Regards,
Dave

**Comment by DonBower** [comment] 2017-06-22 06:33
Hi @davewalter,
Thanks for the advice.
So the "before" state is, well, not much.  I just finished using the bosh-authentication sub-command to initialize Ops Manager.
I'm trying to set all six of the value sets that are on all of the Ops Manager Director tile (IaaS, Director Config, Networks, etc...) and all of them worked, except --director-configuration.
I'm using the current version of OM, 0.23.0.
I am trying to configure Ops Manager 1.9.8
I'm using Concourse 3.1.0
rails_log seems to show it was done.
Is this an error in OpsMan 1.9.8?

[rails_log.txt](https://github.com/pivotal-cf/om/files/1093814/rails_log.txt)

**Comment by davewalter** [comment] 2017-06-23 05:13
Hi @DonBower.

Are you configuring each set of values separately and, if so, in parallel? Ops Manager has some known issues around attempting to configure things in parallel. Have you tried specifying all of the options in a single `configure-bosh` sub-command? This is how we use `om` in our own CI:

```
$ om --target https://ops-manager.com --skip-ssl-validation --username admin --password admin-password configure-bosh --iaas-configuration '{...}' --director-configuration '{...}' --az-configuration '{...}' --networks-configuration '{...}' --network-assignment '{...}'
configuring iaas specific options for bosh tile
configuring director options for bosh tile
configuring availability zones for bosh tile
configuring network options for bosh tile
assigning az and networks for bosh tile
finished configuring bosh tile
```

Regards,
Dave

**Comment by DonBower** [comment] 2017-06-23 18:30
Hi @davewalter,
We are running each of the --XXX-configuration in 6 separate executions of the om-linux command.
And we are running them serialy in the following order:

  echo "Try IaaS Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
    --iaas-configuration "${I_PROPERTIES}" \
  echo ""

  echo "Try Director Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --director-configuration "${D_PROPERTIES}"

  echo "Try AZ Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --az-configuration "${A_PROPERTIES}"

  echo "Try Networks Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --networks-configuration "${N_PROPERTIES}"

  echo "Try Assignments Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --network-assignment "${NA_PROPERTIES}"

  echo "Try Security Config"
  ./${CMD_PATH} --skip-ssl-validation --target "${OPSMAN_URI}" \
   --username "${OPSMAN_USERNAME}" --password "${OPSMAN_PASSWORD}" configure-bosh \
   --security-configuration "${S_PROPERTIES}"

**Comment by davewalter** [comment] 2017-06-24 00:41
Hi @DonBower,

As long as you run them serially, I would have expected you to be fine, but I am curious as to why you don't run them all in a single command?

I don't see anything obvious in the rails log that would indicate that Ops Manager had an obvious problem with the payload. Have you tried manually configuring the Ops Manager with the same values just to confirm that it will accept them? If that works, could you try submitting the request using `om curl` to see if that results in an error or not? You might want to revert the staged changes in the Ops Manager after attempting to configure the director via the UI just so that you know you are starting from a clean slate. I can help you craft the request payload if you need it.

Regards,
Dave

**Comment by davewalter** [comment] 2017-06-26 16:39
Hi @DonBower,

I was just reviewing your issue with my pair and we noticed that we only configure the ntp servers in our CI so there might be an issue with some of the other settings that you are providing. We are going to stand up an environment and try something closer to your set of values to see what happens.

Regards,
Dave

**Comment by davewalter** [comment] 2017-06-26 19:32
Hi @DonBower,

We think we've found the root cause. For some reason, Ops Manager will respond with `200 OK` if there are missing required fields in the request payload, instead of the expected `422 Unprocessable Entity`. In your case, you are missing the AWS access key ID (`s3_blobstore_options.access_key`) and secret (`s3_blobstore_options.secret_key`) for the external S3 blobstore.

Please let me know if adding these properties fixes your issue.

Regards,
Dave

**Comment by DonBower** [comment] 2017-06-27 03:10
I have those properties listed  in a dictionary, as such:
do I need to list each one separately?

    "s3_blobstore_options": {
        "endpoint": "https://s3.amazonaws.com",
        "bucket_name": "s3-le1-inc-pcfopsmanager",
        "access_key_id": "-redacted-",
        "secret_access_key": "-redacted-",
        "signature_version": "4",
        "region": "us-east-1"
    },

**Comment by davewalter** [comment] 2017-07-10 18:51
Hi @DonBower,

Sorry for the long delay. I finally had the chance to stand up an environment and try this with the sample payload you listed. What I found was that the `s3_blobstore_options` key was ignored until I specified `"blobstore_type": "s3"` in my request. Once I added that, I noticed that the keys I was using for the access key ID and secret didn't match the docs for Ops Manager 1.11.4. Once I fixed those, the request configured the director as expected. I know you are using an older version of Ops Manager, so you should check the docs for that version (append `/docs` to your Ops Manager URL) to verify the expected keys for this request. For my installation, I did a browser search for `s3_blobstore_options` and found an example that specified `s3` that looked like this:
```
Example Request with S3 Blobstore options
curl "https://example.com/api/v0/staged/director/properties" \ 
    -X PUT \ 
    -H "Authorization: Bearer UAA_ACCESS_TOKEN" \ 
    -H "Content-Type: application/json" \ 
    -d '{
                "director_configuration": {
                  "ntp_servers_string": "us.pool.ntp.org, time.google.com",
                  "metrics_ip": null,
                  "resurrector_enabled": false,
                  "max_threads": null,
                  "database_type": "internal",
                  "blobstore_type": "s3",
                  "s3_blobstore_options": {
                    "endpoint": "http://some-s3-endpoint.com",
                    "bucket_name": "bucket-name",
                    "access_key": "the-access-key",
                    "secret_key": "the-secret-key",
                    "signature_version": "4",
                    "region": "us-west-1"
                  }
                }
        }'
Example Response
HTTP/1.1 200 OK

  {}
```
Hope this helps.

Regards,
Dave

**Comment by DonBower** [comment] 2017-07-11 02:14
No problem Dave.
Let me give this a throw and see what catches.

Get Outlook for iOS<https://aka.ms/o0ukef>
_____________________________

**Comment by DonBower** [comment] 2017-07-12 04:39
Dave;
I can't use curl at the moment, because BOSH Directory has not been created yet, however, here is the JSON I am using for the om-tool:
{
    "ntp_servers_string": "10.175.255.225, 10.175.255.226",
    "metrics_ip": null,
    "resurrector_enabled": false,
    "enable_post_deploy": true,
    "bosh_recreate_on_next_deploy": false,
    "retry_bosh_deploys": false,
    "keep_unreachable_vms": false,
    "pagerduty_enabled": false,
    "email_notifications": false,
    "blobstore_type": "s3",
    "s3_blobstore_options": {
        "endpoint": "user-supplied-value",
        "bucket_name": "user-supplied-value",
        "access_key_id": "vault-supplied-key",
        "secret_access_key": "vault-supplied-key",
        "signature_version": "4",
        "region": "user-supplied-value"
    },
    "database_type": "external",
    "external_database_options": {
        "host": "user-supplied-value",
        "port": 3306,
        "user": "vault-supplied-key",
        "password": "vault-supplied-key",
        "database": "vault-supplied-key"
    },
    "max_threads": null,
    "director_hostname": null
}
So if I am missing a required field, I am oblivious to it.

**Comment by davewalter** [comment] 2017-07-12 05:05
Hi @DonBower,

I think your keys for the S3 access key ID and secret are incorrect. Try `access_key` and `secret_key` respectively.

Regards,
Dave

**Comment by DonBower** [comment] 2017-07-12 05:15
Hey @davewalter ;
Not sure that's correct for aws.
From a deployed directory manifest:
{
  "blobstore": {
    "provider": "s3",
    "host": "s3-us-west-2.amazonaws.com",
    "s3_port": 443,
    "use_ssl": true,
    "bucket_name": "mybucket",
    "access_key_id": "mykeyid",
    "secret_access_key": "myaccesskey",
    "s3_force_path_style": true,
    "s3_multipart_threshold": 1099511627776,
    "s3_signature_version": "4",
    "s3_region": "us-west-2"
  }
}

**Comment by davewalter** [comment] 2017-07-12 05:23
Hi @DonBower,

Those are the field names in the Ops Manager UI/API. I don't think they match the keys from the director's manifest.

Regards,
Dave

**Comment by DonBower** [comment] 2017-07-12 06:00
Hey Dave;
I'm not sure where you are seeing this, but according to the https://myhost.com/docs#updating-director-and-iaas-properties-experimental, the iaas_configuration uses the other format.
The keys you mentioned are not specified in the example:
    -d '{
                "iaas_configuration": {
                  **"access_key_id"**: "example-access-key",
                  **"secret_access_key"**: "example-aws-secret-key",
                  "iam_instance_profile": "example-instance-profile",
                  "vpc_id": "my-vpc",
                  "security_group": "example-security-group",
                  "key_pair_name": "example-ssh-key",
                  "ssh_private_key": "example-ssh-private-key",
                  "region": "us-east-1"
                },
                "director_configuration": {
                  "ntp_servers_string": "us.pool.ntp.org",
                  "metrics_ip": "1.2.3.4",
                  "resurrector_enabled": true,
                  "max_threads": 1,
                  "database_type": "internal",
                  "blobstore_type": "local"
                },
                "security_configuration": {
                  "trusted_certificates": "—– BEGIN SSL CERTIFICATE —– ... ",
                  "generate_vm_passwords": true
                }
        }'

**Comment by davewalter** [comment] 2017-07-12 15:50
Hi @DonBower,

I checked the docs for a 1.9.16 Ops Manager that we have up at the moment for a patch release of the ERT and I can't find the example that corresponds to the one I from 1.11 that I referenced a couple of days ago. The keys you mentioned are for the `iaas_configuration` section of the API request, not the `director_configuration`. Also, sadly, we aren't using the API to configure the director yet, so the API docs aren't helpful. We have a story in our backlog to investigate using this, but it is still marked as `experimental`, so we have avoided using it until now. Instead, we are performing the same form posts that the Ops Manager UI uses, and the keys for that request are the ones I listed above.

Please give the different keys a try and let me know if it doesn't work.

Regards,
Dave

**Comment by pdelagrave** [comment] 2017-07-12 22:17
Hi, seems related:

```
om -k -t URL -u admin -p pass configure-bosh --director-configuration '{
  "ntp_servers_string": "us.pool.ntp.org",
  "post_deploy_enabled": true,
  "keep_unreachable_vms": true }'
```

Configuring `keep_unreachable_vms` doesn't work for us on OpsMan 1.11.5, it stays unchanged whatever we try.

However, this works:
`om -k -t URL -u admin -p pass curl -p /api/v0/staged/director/properties -x PUT -d '{"director_configuration": {"keep_unreachable_vms": true}}'`

Thanks

Pierre

**Comment by DonBower** [comment] 2017-07-14 03:12
Hi @davewalter and @pdelagrave ;
I'll need to blow away my current foundation before I can try again.
That's scheduled for this weekend, so stay tuned...

I'll all four version of curl vs. configure-bosh and my-keys vs. your keys.
we'll see what throws then...

**Comment by davewalter** [comment] 2017-07-14 14:27
Hi @DonBower,

Please bear in mind that `om configure-bosh` is not currently using the API endpoint that you are hitting with `om curl`, so there could easily be differences between the two. However, I would be surprised if the API payload differed from the example I found in the docs for 1.11.

Also, I am going on vacation tomorrow so another member of the team will be helping you as of Monday.

Regards,
Dave

**Comment by DonBower** [comment] 2017-07-16 17:09
Hello @davewalter and @pdelagrave ;
I was unsuccessful in running any curl commands, and I attribute that to my workstation.
I was successful in running om configure-bosh using the keys you provided.  Also, I found those keys in the om code here:
https://github.com/pivotal-cf/om/blob/9c001a9f1362c07d17c90a3a0a7f6053f1fdcf2f/commands/bosh_form_models.go#L184

For me, this matter is closed, however, There should be some better documentation of what the key names are for inputs, or at least where to best find them.

Thanks for all you help.
-don

**Comment by kkallday** [comment] 2017-07-19 21:20
@DonBower you're right - this is missing from the documentation. There are many parameters you can pass to the director configuration and they are different depending on the IaaS. For instance on this [page](https://github.com/pivotal-cf/om/blob/master/docs/configure-bosh/aws.md), we give a minimal example of the configuration for AWS but not all the potential options. 

I'm going to bring this up with our PM and attempt to work out a way to better address this.

Thanks for bring this to our attention.

**Closed by kkallday** 2017-07-19 21:20 UTC
Labels: scheduled
