### ISSUE TITLE
om is parsing numeric strings as literal numerics

### ISSUE THREAD

**Issue by eoghank** [pivotal-cf/om#352] opened 2019-04-24 12:41 UTC
We have encountered a bug with om (version 0.56.0) and how it is handling strings versus integers. Particularly when we are trying to configure the PKS tile and need to supply the persistent disk types, om is parsing the numeric string as a literal numeric, which then causes it not to match a valid disk type.

From the trace output of om where we are using environment variables for the parameters where the environment variable's value is 51200:

".properties.plan1_selector.active.master_persistent_disk_type":{"value":51200}

 and we've hardcoded the other two disk values which work and those appear as:

".properties.plan2_selector.active.master_persistent_disk_type":{"value":"51200"}

".properties.plan3_selector.active.master_persistent_disk_type":{"value":"51200"}

(note the quotes around the value)

 We've tried many permutations of the env var value to no avail. One such example where we set the value to: \"51200\" results in:

".properties.plan1_selector.active.master_persistent_disk_type":{"value":"\"51200\""}

Which also fails as an invalid value.

One workaround, that is not acceptable for our situation, is to have this variable in a file and override the value there after it has sourced in all the values from the environment. This leads us to believe this is a bug in how om is parsing the environment variables.
Also of note, the quoted value works properly when we pull in the value from a file (via --vars-file) with the double quotes, but we need this to work via the --vars-env option. We've tried many, many permutations of the env var value to no avail, e.g.:

\"51200\"
'\"51200\"'
"\"51200\""
'51200'
\'51200\'

In all cases, the value gets munged with extra and/or stripped quotes (see the trace output example from the first update as an example).

**Comment by kcboyle** [comment] 2019-04-29 19:59
Hi @eoghank! 

Are you suggesting a change for `om interpolate`? 

a little background on that command is that it is a limited feature clone of [`bosh interpolate`](https://bosh.io/docs/cli-int/). `bosh interpolate`, managed by the Cloud Foundry Foundation, works much in the same way. There are some limitations around parsing strings that the bosh team is working to address, and `om interpolate` can follow suit once completed (not the exact issue, but related -- https://github.com/cloudfoundry/bosh-cli/issues/248).

This is not a bug in how we parse environment variables, but rather an issue in the gopkg.in/yaml.v2 library (see h4xnoodle's [comment](https://github.com/cloudfoundry/bosh-cli/issues/248#issuecomment-449761065)). 

In practice on our team, we use [Concourse](concourse-ci.org) to manage our secrets by making use of Concourse's transient containers, so the values are not being _permanently_ written to disk (Concourse makes use of aggressively transient containers).

Could you explain why writing a numerical value to a file is unacceptable? I understand the use case for secrets not being written to disk, but would like to understand more your use case for a value that does not appear to be a secret. Perhaps if we have more context we can help you figure out a better workaround until the gopkg yaml parser can implement a fix.

**Comment by kcboyle** [comment] 2019-05-06 17:39
Hello again, @eoghank! Just wanted to follow up based on the post above. If you could give us some more information, we'd love to have this conversation with you.

**Comment by kcboyle** [comment] 2019-05-13 18:26
From an external conversation. For community visibility, editing and posting the conversation here:

This already works properly in ‘bosh int’:

-          Set the env variable with escaped quotes, e.g. export TEST_pks_p1_master_persistent_disk=\“51200\”

-          bosh int --vars-env=TEST  pks-tile-template.yml

o   The resulting output properly quotes the numeric string value:

§    .properties.plan1_selector.active.master_persistent_disk_type:

§      value: “51200"

This is the behavior we’d expect from om as well, and based on their feedback below, it should already be working. Or if someone is doing a limited feature set, can they not import this bosh int feature into om int?

To make testing simpler, we can replicate the bad behavior by using om’s int command. With the same TEST_pks_p1_master_persistent_disk variable as above - which works with bosh int – we see om breaking:

-          om-linux-latest interpolate --vars-env TEST -c pks-tile-template.yml

-          product-name: pivotal-container-service

-          product-properties:

-            .properties.plan1_selector.active.master_persistent_disk_type:

-              value: ‘“51200”’

**Comment by kcboyle** [comment] 2019-05-13 18:28
All of this said, it seems like the solution to this problem is to solve the "so is the problem that they need integers to be quoted, but om interpolate strips the quotes, or that om interpolate should be putting integers in quotes?" problem.

**Comment by kcboyle** [comment] 2019-05-20 21:30
This will be released in the next version of `om` (Currently: 1.0.1. Potentially 1.1.0 depending on if new features are added -- see [Changelog](https://github.com/pivotal-cf/om/blob/master/CHANGELOG.md) for more details)

**Closed by kcboyle** 2019-05-20 21:30 UTC
Labels: accepted, pr welcome
