### ISSUE TITLE
download-product fails to download product's stemcell if the product dependencies include windows and linux stemcells

### ISSUE THREAD

**Issue by jvshahid** [pivotal-cf/om#398] opened 2019-07-08 14:33 UTC
Steps to reproduce:
-----------------

```
om download-product -f p-clamav-mirror*.pivotal -p p-clamav-addon -o . --pivnet-api-token <token> --product-version 2.0.0 --stemcell-iaas aws --download-stemcell
```

Actual behavior:
---------------------

OM cli fails to download the stemcell with the following error:

```
Downloading stemcell
could not execute "download-product": could not download stemcell: could not fetch the release for stemcells-ubuntu-xenial 2019.7: release not found for version: '2019.7'
```

From my understanding of [this code](https://github.com/pivotal-cf/om/blob/9f3da329b7cc520176b33fe4304ee48156eb7890/download_clients/pivnet_client.go#L164-L183), the bug appears to be due to the usage of the highest stemcell version regardless of the stemcell type.  In this case, the latest stemcell version is `2019.7`.

Expected behavior:
------------------

I am not exactly sure what the expected behavior should be in this case.  At the very least the cli should keep track of the stemcell slug that corresponds to the version picked.  I also feel there is a missing flag to download-product in order to select the stemcell type, i.e. windows vs ubuntu-xenial, to download.

**Comment by kcboyle** [comment] 2019-07-24 22:27
Questions that need answers for this issue:
- How does PivNet handles stemcell dependencies?
- we should also explore being able to specify the Windows v Linux stemcell.

Windows stemcells cannot be downloaded from pivnet unless you are a pivotal employee, so adding the ability to choose an IAAS seems like the wrong way to go. 

That said, there is a fix we could do is more intelligently look in the tile manifest when determining the stemcell to download, and ignore windows stemcells for the above reason.

**Comment by jghiloni** [comment] 2019-08-12 16:16
I've been trying to reproduce this with the `p-clamav-mirror` tile and PKS 1.5, and have been unable to reproduce. @jvshahid is this still an issue? Both cases, I ran a command equivalent to your description, and received no error.

**Comment by kcboyle** [comment] 2019-08-19 19:44
@jvshahid a friendly bump for you on this thread! would like to know if this is still an issue, or if we can close this out

**Comment by kcboyle** [comment] 2019-08-29 17:57
@jvshahid, We're going to close this issue, due to inactivity since we have been unable to reproduce the problem. Please feel free to reopen if necessary!

**Closed by kcboyle** 2019-08-29 17:57 UTC
Labels: unscheduled
