### ISSUE TITLE
Multi-AZ configuration fails on PCF 1.11

### ISSUE THREAD

**Issue by dhrapson** [pivotal-cf/om#89] opened 2017-07-11 14:03 UTC
When using om to configure multiple AZs against Ops Manager 1.11.3 I get a 500 HTTP response and the following error (hidden amongst a whole bunch of HTML): 

<pre>ArgumentError</pre>
<pre>missing keyword: name</pre>

The command I'm executing is just setting the az-configuration, having separately done directory-configuration and the iaas-configuration first:

om --target https:/opsman.example.org -k    --username "myname"    --password "mypassword"    configure-bosh   --az-configuration "{\"availability_zones\":[{\"name\":\"Bob\",\"cluster\":\"bobcluster\",\"resource_pool\":\"bobpool\"},{\"name\":\"Steve\",\"cluster\":\"stevecluster\",\"resource_pool\":\"stevepool\"}]}"

Running the same command with only 1 element in the availability_zones array succeeds. 

The workaround I'm using in the interim is to 'om curl' the AZs API endpoint as follows:

om --target https:/opsman.example.org -k    --username "myname"    --password "mypassword"    curl  -x PUT  -p '/api/v0/staged/director/availability_zones'  --data 'the_az_json'

**Comment by davewalter** [comment] 2017-07-14 00:09
Hi @dhrapson,

This looks like you are running on vSphere, correct? I'm not at all surprised that this doesn't work as our own vSphere environments are all single AZ. I'm going to leave this issue open for now and discuss it with our PM to prioritize bringing our vSphere support in line with the other infrastructures we work with.

Regards,
Dave

**Comment by davewalter** [comment] 2017-07-14 00:20
Hi @dhrapson,

Actually, if this is vSphere, then this is a duplicate of issue #33, so I am going to close this in favour of that issue. Please feel free to reopen this issue if my assumption of which infrastructure you are using is wrong.

Regards,
Dave

**Closed by davewalter** 2017-07-14 00:20 UTC
Labels: scheduled
